<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Applying Smart Device Usage Trends to Bellabeat Products</title>

<script src="site_libs/header-attrs-2.13/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="site_libs/pagedtable-1.1/js/pagedtable.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Bellabeat Case Study</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="final_report.html">Final Report</a>
</li>
<li>
  <a href="data_cleaning_process.html">Data Cleaning Process</a>
</li>
<li>
  <a href="final_report_code.html">Final Report Code</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Applying Smart Device Usage Trends to
Bellabeat Products</h1>

</div>


<div id="business-tasks" class="section level2">
<h2>1. Business Tasks</h2>
<ol style="list-style-type: decimal">
<li>What are some trends in smart device usage?</li>
<li>How could these trends apply to Bellabeat customers?</li>
<li>How could these trends help influence Bellabeat marketing
strategy?</li>
</ol>
<div id="load-packages-and-cleaned-datasets" class="section level4">
<h4>2. Load packages and cleaned datasets</h4>
<pre class="r"><code>library(tidyverse)
library(data.table)
library(viridisLite)
library(viridis)
library(ggplot2)
library(htmltools)

# Read csv files
daily_activity_clean &lt;- read_csv(&quot;daily_activity_clean.csv&quot;, show_col_types = FALSE)
hourly_activity_clean &lt;- read_csv(&quot;hourly_activity_clean.csv&quot;, show_col_types = FALSE)</code></pre>
</div>
<div id="summary-statistics-about-daily-activities"
class="section level4">
<h4>3. Summary statistics about daily activities</h4>
<pre class="r"><code>summary(daily_activity_clean$TotalSteps)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##       0    3818    7441    7671   10734   36019</code></pre>
<p>Users took an average of 7671 steps in a day.</p>
<pre class="r"><code>summary(daily_activity_clean$Calories)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##      52    1834    2144    2313    2794    4900</code></pre>
<p>Users burned an average of 2313 Calories a day.</p>
<pre class="r"><code>summary(daily_activity_clean$TotalDistance)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   0.000   2.645   5.265   5.513   7.720  28.030</code></pre>
<p>Users travelled an average distance of 5.513 km (3.4 mi) a day.</p>
<pre class="r"><code>summary(daily_activity_clean$VeryActiveMinutes)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    0.00    0.00    4.00   21.26   32.00  210.00</code></pre>
<p>Users spent an average of 21 total minutes in very active activity a
day.</p>
<pre class="r"><code>summary(daily_activity_clean$FairlyActiveMinutes)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    0.00    0.00    7.00   13.62   19.00  143.00</code></pre>
<p>Users spent an average of 14 total minutes in fairly active activity
a day.</p>
<pre class="r"><code>summary(daily_activity_clean$LightlyActiveMinutes)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##     0.0   128.0   199.0   193.6   264.2   518.0</code></pre>
<p>Users spent an average of 194 total minutes (about 3 hours) in
lightly active activity a day.</p>
<pre class="r"><code>summary(daily_activity_clean$SedentaryMinutes)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##     0.0   729.0  1057.0   989.3  1226.0  1440.0</code></pre>
<p>Users spent an average of 989 total minutes (about 16 hours) in
sedentary activity a day.</p>
</div>
</div>
<div
id="is-there-a-relationship-between-average-steps-and-days-of-the-week"
class="section level2">
<h2>4. Is there a relationship between average steps and days of the
week?</h2>
<p><img src="final_report_files/figure-html/unnamed-chunk-9-1.png" width="672" />
#### 5. How active are the participants?</p>
<p><img src="final_report_files/figure-html/unnamed-chunk-10-1.png" width="672" />
WHO: 150–300 minutes of moderate-intensity aerobic physical activity; or
at least 75–150 minutes of vigorous-intensity aerobic physical activity.
Active: ModerateActiveMinutes &gt; 300 or VeryActiveMinutes &gt; 150
Normal: ModerateActiveMinutes &gt;= 150 &amp; ModerateActiveMinutes
&lt;= 300) or (VeryActiveMinutes &gt;= 75 &amp; VeryActiveMinutes &lt;=
150) Sedentary: ModerateActiveMinutes &lt; 150 or VeryActiveMinutes &lt;
75</p>
<p>About half of participants have activity level considered normal,
about a quarter are active and a quarter sedentary.</p>
<div id="what-is-the-percentage-of-users-that-meet-10000-steps-a-day"
class="section level4">
<h4>6. What is the percentage of users that meet 10,000 steps a
day?</h4>
<p><img src="final_report_files/figure-html/unnamed-chunk-11-1.png" width="672" />
About 65% of days respondents met 10,000 steps goal.</p>
</div>
<div id="is-there-a-relationship-between-total-intensity-and-calories"
class="section level4">
<h4>8. Is there a relationship between Total Intensity and
calories?</h4>
<pre><code>## `geom_smooth()` using method = &#39;gam&#39; and formula &#39;y ~ s(x, bs = &quot;cs&quot;)&#39;</code></pre>
<p><img src="final_report_files/figure-html/unnamed-chunk-12-1.png" width="672" />
Intensity and Calories are directly related. The more intensity the
exercises are, the more calories are burned.</p>
<pre class="r"><code>print(hourly_intensity_plot &lt;- hourly_activity_clean %&gt;%
  group_by(hours= hour(ActivityHour), wday) %&gt;%
ggplot(aes(hours, wday)) +
  geom_tile(aes(fill = TotalIntensity), colour = &quot;white&quot;) +
  scale_fill_distiller(palette = &quot;YlOrRd&quot;, direction = 1) +
  scale_x_continuous(breaks = 0:23) +
  theme_minimal() +
  theme(
    legend.position = &quot;bottom&quot;,
    legend.key.width = unit(2, &quot;cm&quot;),
    panel.grid = element_blank()
  ) +
   scale_fill_viridis(option = &quot;magma&quot;, 
                     direction = -1, 
                     name = &quot;TotalIntensity&quot;) +
  labs(title = &quot;Total Intensity by Hour of Day&quot;, x = &quot;&quot;, y = &quot;&quot;) +
  coord_equal()
)</code></pre>
<pre><code>## Scale for &#39;fill&#39; is already present. Adding another scale for &#39;fill&#39;, which
## will replace the existing scale.</code></pre>
<p><img src="final_report_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>Time of day users performed most intensive activities are Saturdays,
Fridays and Wednesdays between noon and 5 pm.</p>
</div>
<div id="relationship-between-days-of-the-month-and-steps-taken"
class="section level4">
<h4>9. Relationship between days of the month and steps taken</h4>
<p><img src="final_report_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
</div>
<div id="recommendations" class="section level4">
<h4>10. Recommendations</h4>
<p>The marketing recommendations concluded from the insights of this
case study should be focused on providing features, notifications,
reminders for fitness tracking with an aim of encouraging physical
activity.</p>
<p>The three possible marketing recommendations for Bellabeat are as
follows:</p>
<ol style="list-style-type: decimal">
<li><p>Digital campaigns that show Bellabeat Le prioritizing tracking
tools to keep users comparing , send reminders to get upand get moving.,
tracking menstrual cycle, track meditations and sleep habits, as a
stylish, classic accessory with full fitness tracking features. Top
features: breathing, notifications and calls, workouts Standard
features: clock, faces, sleep, timer, health metrics, Missing features:
music, GPS signal, payment, size</p></li>
<li><p>Notifications/email reminders that show the benefits of physical
activity. The</p></li>
<li><p>Prioritize sharing insights through dashboards with the user so
they can make decisions on their health.</p></li>
</ol>
<p>The fitness trackers may be motivating users to develop healthy
habits and increase wellness by providing metrics on their activities. *
We can focus on the advantages of using Bellabeat app * Create more
reporting, comparing and trend options for activity tracking, METs
vs. calories, etc. * More charts or graphs comparing exercise sessions.
* Create insights such as “this is the longest distance you’ve run” or
“this was your third fastest 5k”. * Filter exercise types such as
elliptical, running, walking, etc. * Adding a feature to remind users
when they have been idle for a period of time. * For users that want to
lose weight or burn more overall calories, adding a reward or
notification to celebrate would be very motivating.</p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
