<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Final Report Code</title>

<script src="site_libs/header-attrs-2.13/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="site_libs/pagedtable-1.1/js/pagedtable.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Bellabeat Case Study</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="final_report.html">Final Report</a>
</li>
<li>
  <a href="data_cleaning_process.html">Data Cleaning Process</a>
</li>
<li>
  <a href="final_report_code.html">Final Report Code</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Final Report Code</h1>

</div>


<div id="load-packages-and-cleaned-datasets" class="section level2">
<h2>1. Load packages and cleaned datasets</h2>
<pre class="r"><code>library(tidyverse)
library(data.table)
library(viridisLite)
library(viridis)</code></pre>
<pre class="r"><code># Load datasets
daily_activity_clean &lt;- fread(&quot;C:/Users/LG 14z/Documents/R/nhubao.github.io/daily_activity_clean.csv&quot;)
hourly_activity_clean &lt;- fread(&quot;C:/Users/LG 14z/Documents/R/nhubao.github.io/hourly_activity_clean.csv&quot;)</code></pre>
</div>
<div id="summary-statistics-about-daily-activities"
class="section level2">
<h2>2. Summary statistics about daily activities</h2>
<ol style="list-style-type: decimal">
<li>How many steps did users take in a day?</li>
</ol>
<pre class="r"><code>summary(daily_activity_clean$TotalSteps)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##       0    3818    7441    7671   10734   36019</code></pre>
<p>Users took an average of 7671 steps in a day.</p>
<pre class="r"><code>summary(daily_activity_clean$Calories)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##      52    1834    2144    2313    2794    4900</code></pre>
<p>Users burned an average of 2313 Calories a day.</p>
<pre class="r"><code>summary(daily_activity_clean$TotalDistance)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   0.000   2.645   5.265   5.513   7.720  28.030</code></pre>
<p>Users travelled an average distance of 5.513 km a day.</p>
<pre class="r"><code>summary(daily_activity_clean$VeryActiveMinutes)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    0.00    0.00    4.00   21.26   32.00  210.00</code></pre>
<p>Users spent an average of 21 total minutes in very active activity a
day.</p>
<pre class="r"><code>summary(daily_activity_clean$FairlyActiveMinutes)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    0.00    0.00    7.00   13.62   19.00  143.00</code></pre>
<p>Users spent an average of 14 total minutes in fairly active activity
a day.</p>
<pre class="r"><code>summary(daily_activity_clean$LightlyActiveMinutes)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##     0.0   128.0   199.0   193.6   264.2   518.0</code></pre>
<p>Users spent an average of 194 total minutes (about 3 hours) in
lightly active activity a day.</p>
<pre class="r"><code>summary(daily_activity_clean$SedentaryMinutes)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##     0.0   729.0  1057.0   989.3  1226.0  1440.0</code></pre>
<p>Users spent an average of 989 total minutes (about 16 hours) in
sedentary activity a day.</p>
</div>
<div
id="is-there-a-relationship-between-average-steps-and-days-of-the-week"
class="section level2">
<h2>3. Is there a relationship between average steps and days of the
week?</h2>
<pre class="r"><code># Plot average steps by days of week
steps_week_plot &lt;- daily_activity_clean %&gt;% group_by(wday) %&gt;% summarise(MeanTotalSteps = mean(TotalSteps)) %&gt;% 
 ggplot(aes(x = wday,
             y = MeanTotalSteps,
             fill = MeanTotalSteps)) +
  geom_col(width = 0.7)+
  labs(title = &quot;Average Daily Steps by Days of Week&quot;,
       x = NULL,
       y = &quot;Average Daily Steps&quot;) +
  guides(fill = &quot;none&quot;) +
  geom_text(aes(label = round(MeanTotalSteps)),
            color = &quot;white&quot;,
            vjust = 1.5) +
  scale_fill_distiller(palette = &quot;RdPu&quot;, direction = 1)</code></pre>
<p>Users took the most steps on Tuesdays and Saturdays and least on
Sundays.</p>
</div>
<div id="what-are-the-activity-levels-of-users" class="section level2">
<h2>4. What are the activity levels of users?</h2>
<pre class="r"><code># Plot activity level distribution
activity_level_plot &lt;- daily_activity_clean %&gt;% 
  group_by(ActivityLevel) %&gt;% 
  count() %&gt;% 
  mutate(Percent = n / nrow(daily_activity_clean)) %&gt;% 
  ggplot(aes(x = ActivityLevel, 
             y = Percent, 
             fill = ActivityLevel)) +
  geom_col(width = 0.75) +
  labs(title = &quot;Distribution of Activity Levels&quot;, 
       x = NULL, 
       y = &quot;% of Records&quot;) +
  guides(fill = &quot;none&quot;) +
  geom_text(aes(label = paste0(round(Percent * 100, 1), &quot;%&quot;)), 
            color = &quot;white&quot;,
            vjust = 1.5)</code></pre>
<p>About half of records were tracked as normal activity, 22.3% as
active and 26.7% as sedentary.</p>
</div>
<div id="what-is-the-percentage-of-users-that-meet-10000-steps-a-day"
class="section level2">
<h2>5. What is the percentage of users that meet 10,000 steps a
day?</h2>
<pre class="r"><code>ten_thousand_steps_plot &lt;- daily_activity_clean %&gt;% 
  group_by(Meets10000Steps) %&gt;% 
  count() %&gt;% 
  mutate(Percent = n / nrow(daily_activity_clean)) %&gt;% 
  ggplot(aes(x = Meets10000Steps, 
             y = Percent, 
             fill = Meets10000Steps)) +
  geom_col(width = 0.75) +
  labs(title = &quot;Percent of daily records that meet 10,000 steps goal&quot;, 
       x = NULL, 
       y = &quot;% of Records&quot;) +
  guides(fill = &quot;none&quot;) +
  geom_text(aes(label = paste0(round(Percent * 100, 1), &quot;%&quot;)), 
            color = &quot;white&quot;,
            vjust = 1.5)</code></pre>
<p>About 65% of days respondents met 10,000 steps goal.</p>
</div>
<div id="top-3-highest-total-steps-per-day" class="section level2">
<h2>6. Top 3 highest total steps per day</h2>
<pre class="r"><code> # Top 3 highest Total Steps per day by Id
top3_daily_steps &lt;- daily_activity_clean %&gt;%
  arrange(desc(TotalSteps)) %&gt;% 
  group_by(Id) %&gt;%
  slice(1:3) %&gt;%
  select(Id, ActivityDate, TotalSteps)

# Plot for highest total steps
 top3_steps_plot &lt;- top3_daily_steps %&gt;% 
  ggplot(aes(x = Id, 
             y = TotalSteps, 
             fill = TotalSteps)) +
  geom_col(width = 0.55, position=&quot;dodge2&quot;) +
  labs(title = &quot;Top 3 most steps taken by each user&quot;, 
       x = NULL, 
       y = &quot;Daily Steps&quot;) +
   scale_fill_distiller(palette = &quot;YlOrRd&quot;, direction = 1) +
   theme(axis.text.x = element_text(angle = 90))</code></pre>
</div>
<div
id="whats-the-relationship-between-steps-taken-in-a-day-and-sedentary-minutes"
class="section level2">
<h2>7. What’s the relationship between steps taken in a day and
sedentary minutes?</h2>
<pre class="r"><code>sedentary_steps_plot &lt;- ggplot(daily_activity_clean, aes(x=SedentaryMinutes, y = TotalSteps)) + geom_point() +
  labs(title = &quot;Steps Taken in a day vs. Sedentary Minutes&quot;,
       x = &quot;Sedentary Minutes&quot;,
       y = &quot;Steps taken in a day&quot;,
       size = &quot;&quot;) + geom_smooth()</code></pre>
</div>
<div id="is-there-a-relationship-between-totalintensity-and-calories"
class="section level2">
<h2>8. Is there a relationship between TotalIntensity and calories?</h2>
<pre class="r"><code>Intensity_C_plot &lt;- ggplot(hourly_activity_clean, aes(x=TotalIntensity, y = Calories)) + geom_point() +
  labs(title = &quot;Total Intensity vs. Calories&quot;,
       x = &quot;Total Intensity&quot;,
       y = &quot;Calories&quot;,
       size = &quot;&quot;) + geom_smooth()</code></pre>
</div>
<div id="heatmap-hourly-intensity" class="section level2">
<h2>9. Heatmap Hourly Intensity</h2>
<pre class="r"><code>hourly_intensity_plot &lt;- hourly_activity_clean %&gt;%
  group_by(hours= hour(ActivityHour), wday) %&gt;%
ggplot(aes(hours, wday)) +
  geom_tile(aes(fill = TotalIntensity), colour = &quot;white&quot;) +
  scale_fill_distiller(palette = &quot;YlOrRd&quot;, direction = 1) +
  scale_x_continuous(breaks = 0:23) +
  theme_minimal() +
  theme(
    legend.position = &quot;bottom&quot;,
    legend.key.width = unit(2, &quot;cm&quot;),
    panel.grid = element_blank()
  ) +
   scale_fill_viridis(option = &quot;magma&quot;, 
                     direction = -1, 
                     name = &quot;TotalIntensity&quot;) +
  labs(title = &quot;Total Intensity by Hour of Day&quot;, x = &quot;&quot;, y = &quot;&quot;) +
  coord_equal()</code></pre>
<pre><code>## Scale for &#39;fill&#39; is already present. Adding another scale for &#39;fill&#39;, which
## will replace the existing scale.</code></pre>
</div>
<div
id="is-there-a-relationship-between-total-steps-and-days-of-the-month"
class="section level2">
<h2>10. Is there a relationship between total steps and days of the
month?</h2>
<pre class="r"><code># heatmap of Total Steps for the complete month
month_steps_plot &lt;-
daily_activity_clean %&gt;%
ggplot(aes(wday, y=week)) +
  geom_tile(aes(fill = TotalSteps), color = &quot;white&quot;, size = .5) +
  geom_text(aes(label = day)) + 
  scale_fill_viridis(option = &quot;magma&quot;, 
                     direction = -1, 
                     name = &quot;Total Steps&quot;) +
  labs(title = &quot;Total Steps by Date&quot;, x = &quot;April to May&quot;, y = &quot;&quot;) + 
  scale_y_continuous(trans = &quot;reverse&quot; ) +
  scale_x_discrete(position = &quot;top&quot;)</code></pre>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
